project:
  type: website
  output-dir: docs

website:
  title: "Portafolio - Luis Carreño"
  navbar:
    left:
      - text: Luis Carreño
        menu:
          - text: English
            href: about.qmd
          - text: Português
            href: about-pt.qmd
          - text: Español
            href: about-es.qmd
      - text: Projects
        href: index.qmd
      - text: Books
        href: Books.qmd
      - text: Blog
        href: Blog.qmd
      - text: Dashboards
        href: Dashboards.qmd
      - text: Machine Learning & IA
        href: Machine Learning & IA.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lcarrenoy
      - icon: linkedin
        href: https://www.linkedin.com/in/luis-alberto-carreño/     

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    fontsize: 1.5 rem
    mainfont: arial
    monofont: courier new
    css: styles.css
    toc: true
    code-link: true
    code-fold: show
    code-block-bg: "lightblue"
